// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-st-PHHMdBx8rSQvw4L_K1sOlyhXXjDM',
    appId: '1:258205921546:web:b5a3e8aa50fdd85b128af3',
    messagingSenderId: '258205921546',
    projectId: 'fidelite-pizzas',
    authDomain: 'fidelite-pizzas.firebaseapp.com',
    storageBucket: 'fidelite-pizzas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9gayGwDPy-uavN8XN1jky50fZupFw5XM',
    appId: '1:258205921546:android:d75012a8b4c116ca128af3',
    messagingSenderId: '258205921546',
    projectId: 'fidelite-pizzas',
    storageBucket: 'fidelite-pizzas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjfJpfc3CebiTqBv6HXtcGLYuysVaBqA',
    appId: '1:258205921546:ios:06dc39ce744177cf128af3',
    messagingSenderId: '258205921546',
    projectId: 'fidelite-pizzas',
    storageBucket: 'fidelite-pizzas.firebasestorage.app',
    iosBundleId: 'com.tomtom.gestioncompta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFjfJpfc3CebiTqBv6HXtcGLYuysVaBqA',
    appId: '1:258205921546:ios:06dc39ce744177cf128af3',
    messagingSenderId: '258205921546',
    projectId: 'fidelite-pizzas',
    storageBucket: 'fidelite-pizzas.firebasestorage.app',
    iosBundleId: 'com.tomtom.gestioncompta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-st-PHHMdBx8rSQvw4L_K1sOlyhXXjDM',
    appId: '1:258205921546:web:2035090cdea3099e128af3',
    messagingSenderId: '258205921546',
    projectId: 'fidelite-pizzas',
    authDomain: 'fidelite-pizzas.firebaseapp.com',
    storageBucket: 'fidelite-pizzas.firebasestorage.app',
  );
}
